### ISSUE TITLE
ethereum-to-graphql not exist on npm

### ISSUE THREAD

**Issue by katopz** [sogoiii/ethereum-to-graphql#1]
https://www.npmjs.com/search?q=ethereum-to-graphql&page=1&ranking=optimal

Or maybe I miss something?

**Comment by sogoiii** [comment]
I have yet to publish this repo. It is still experimental at the moment. I have it working in some form, but its not generic enough.

**Comment by katopz** [comment]
This is super cool project I found lately!
Do you have a plan or road map?
I think I can help somehow :)

Thanks!

**Comment by sogoiii** [comment]
@katopz hey, I know its been an a while. But i moved the project to another [repo](https://github.com/hellosugoi/Ethereum-to-GraphQL). Its in much better state. I also created issues if you wanted to help by contributing.
