### ISSUE TITLE
All test failed with latest package

### ISSUE THREAD

**Issue by katopz** [sogoiii/ethereum-to-graphql#2]
All test failed with...
```
    "graphql": "^0.11.7",
    "truffle-contract": "^3.0.0",
    "web3": "^1.0.0-beta.24"
```

**Comment by sogoiii** [comment]
Hey Katopz! 

What kind of error did you see?

**Comment by katopz** [comment]
Hey sogoiiI, :)

From server is
```
Inside sourceFN error ------------------------
```
And from test is mostly `undefined` and `null` results there so it all failed.
I think`"web3": "^1.0.0-beta.24"` is a problem here, last know good is . `"web3": "^0.19.0"`

Thanks

**Comment by katopz** [comment]
Aw snap! I wake up with clean install, redo all stuff and it working now :octocat: 
Sorry for false alarm.
