### ISSUE TITLE
Error: MetaCoin has not been deployed to detected network (network/artifact mismatch)

### ISSUE THREAD

**Issue by elie222** [sogoiii/ethereum-to-graphql#3]
I get this error after setting it all up:
```
Error: MetaCoin has not been deployed to detected network (network/artifact mismatch)
```

I copied the `MetaCoin.json` to my own project. Any idea what the issue is?
Graphiql is aware of the fields to query for.

For this request:
```
{
  getBalanceInEth(addr: "0x22c127f05b6c0e731ddd8a377de555f3118e2389"){
    value {
      string
      int
    }
  }
}
```

I get this response:
```
{
  "errors": [
    {
      "message": "Error: MetaCoin has not been deployed to detected network (network/artifact mismatch)",
      "locations": [
        {
          "line": 29,
          "column": 3
        }
      ],
      "path": [
        "getBalanceInEth"
      ]
    }
  ],
  "data": {
    "getBalanceInEth": null
  }
}
```

And I see:
```
Inside sourceFN error ------------------------
```
in the node console after making the request.

**Comment by sogoiii** [comment]
Hello @elie222,

Are you using testrpc? When you copied your metaCoin.json file, what network was that deployed to? I suspect that maybe you are not talking to the correct Ethreum Node.

In the setup code block, I have a line `const url = 'http://localhost:8545'` that defines the location of the Ethereum node. Was that set properly?

**Comment by sogoiii** [comment]
@elie222 hey, I know its been an a while. But i moved the project to another [repo](https://github.com/hellosugoi/Ethereum-to-GraphQL). Its in much better state. I also created issues if you wanted to help by contributing.
